# -*- coding: utf-8 -*-
"""ailearning

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dViQYo5-q0gf3Nplvgag5QBik_x5TMPH
"""

import pandas as pd

url = "https://raw.githubusercontent.com/woyou66/ai/master/Salary_Data.csv"
data = pd.read_csv(url)
data
x = data["YearsExperience"]
y = data["Salary"]

import matplotlib.pyplot as plt

plt.scatter(x, y, marker = "x", color = "red")
plt.title("year - salary")
plt.xlabel("year")
plt.ylabel("salary")
plt.show()

# y = w * x + b
w = 0
b = 0
def plot_pred(w, b):
  y_pred = x * w + b
  plt.plot(x, y_pred, color = "blue", label = "prediction line")
  plt.scatter(x, y, marker = "x", color = "red", label = "real data")
  plt.title("year - salary")
  plt.xlabel("year")
  plt.ylabel("salary")
  plt.xlim([0, 12])
  plt.ylim([-60, 140])
  plt.legend()
  plt.show()

plot_pred(0, 0)

from ipywidgets import interact

interact(plot_pred, w = (-100, 100, 1), b = (-100, 100, 1))